name: Generate PDF
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: TFG.tex

    - name: Move PDF to build folder
      run: |
        mkdir -p build
        mv TFG.pdf build/

    - name: Create index.html for redirect
      run: |
        echo '<!DOCTYPE html>' > build/index.html
        echo '<html>' >> build/index.html
        echo '<head>' >> build/index.html
        echo '   <meta http-equiv="refresh" content="0; url=http://tfg.matvey.es/TFG.pdf" />' >> build/index.html
        echo '</head>' >> build/index.html
        echo '<body>' >> build/index.html
        echo '   If you are not redirected, <a href="http://tfg.matvey.es/TFG.pdf">click here</a>.' >> build/index.html
        echo '</body>' >> build/index.html
        echo '</html>' >> build/index.html

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build
        branch: gh-pages

       
        
